language: groovy
jdk:
  - oraclejdk7
branches:
  only:
    - master

before_install:
  - curl -s get.sdkman.io | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - echo "sdkman_auto_answer=true" >> $HOME/.sdkman/etc/config
  - sdk version
  - sdk install gradle -y
  - sdk install grails 2.2.2
  
script: 
  - grails refresh-dependencies
  - grails test-app unit: SigaParserSpec
  - grails run-app -Dserver.port=7070
